// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdzhmpbwcbodwozxgyub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkemhtcGJ3Y2JvZHdvenhneXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTQ0NTMsImV4cCI6MjA2MTczMDQ1M30.1JXT9eZ3TMF86UM6PHzOzJHuEnKtiuRu6iG4uGdjjZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);